aggregation_level: category
model_name: mlp
model_family: dl
features:
  enabled: true
config:
  history_length: 39
  hidden_size: 64
  n_blocks: 2
  n_layers: 2
  epochs: 160
  batch_size: 16
  learning_rate: 0.0007
  weight_decay: 0.0001
  device: cpu
  scaler_type: robust
  max_steps: 160
used_feature_columns: []
seed: 42
